## Build Image
kind: pipeline
name: default

steps:
- name: test
  image: digitalpatterns/node:4
  commands:
    - npm install
    - npm run cover
  when:
    event: push

- name: build_push_to_docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: digitalpatterns/form-builder
    tags:
      - ${DRONE_COMMIT_SHA}
  when:
    branch: master
    event: push

- name: deploy_to_dev
  image: quay.io/ukhomeofficedigital/kd
  secrets:
    - DEV_FORM_BUILDER_NAME
    - DEV_WHITELIST
    - DEV_FORM_BUILDER_KUBE_NAMESPACE
    - DEV_KUBE_SERVER
    - DEV_KUBE_TOKEN
    - DEV_FORM_BUILDER_APP_CONFIG
    - DEV_FORM_BUILDER_PORT
    - DEV_FORM_BUILDER_URL
    - ELF_NGINX_PROXY_IMAGE_TAG
    - ELF_NGINX_PROXY_IMAGE_REPO
    - ELF_FORM_BUILDER_IMAGE_REPO
  commands:
    - export FORM_BUILDER_NAME=$${DEV_FORM_BUILDER_NAME}
    - export WHITELIST=$${DEV_WHITELIST}
    - export KUBE_NAMESPACE=$${DEV_FORM_BUILDER_KUBE_NAMESPACE}
    - export KUBE_SERVER=$${DEV_KUBE_SERVER}
    - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
    - export FORM_BUILDER_APP_CONFIG=$${DEV_FORM_BUILDER_APP_CONFIG}
    - export FORM_BUILDER_PORT=$${DEV_FORM_BUILDER_PORT}
    - export FORM_BUILDER_URL=$${DEV_FORM_BUILDER_URL}
    - export NGINX_PROXY_IMAGE_TAG=$${ELF_NGINX_PROXY_IMAGE_TAG}
    - export NGINX_PROXY_IMAGE_REPO=$${ELF_NGINX_PROXY_IMAGE_REPO}
    - export FORM_BUILDER_IMAGE_REPO=$${ELF_FORM_BUILDER_IMAGE_REPO}
    - export FORM_BUILDER_IMAGE_TAG=${DRONE_COMMIT_SHA}
    - kd --insecure-skip-tls-verify -f kube/secret.yml
    - kd --insecure-skip-tls-verify -f kube/network-policy.yml
    - kd --insecure-skip-tls-verify -f kube/service.yml
    - kd --insecure-skip-tls-verify -f kube/deployment.yml
    - kd --insecure-skip-tls-verify -f kube/ingress.yml
  when:
    environment: dev
    event: deployment
