kind: pipeline
name: default

## Build Public Image
steps:
- name: image_to_docker_hub
  image: plugins/docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    repo: digitalpatterns/form-builder
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
  when:
    branch:
      - master
    event:
      - push
