
## Build Public Image
pipeline:

  build_push_to_ecr:
    image: quay.io/ukhomeofficedigital/ecr:latest
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/cop/form-builder
    build_args:
      - APP_BUILD=${DRONE_COMMIT_SHA}
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_FORM_BUILDER_NAME
      - DEV_WHITELIST
      - DEV_FORM_BUILDER_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_FORM_BUILDER_APP_CONFIG
      - DEV_FORM_BUILDER_PORT
    commands:
      - export FORM_BUILDER_NAME=$${DEV_FORM_BUILDER_NAME}
      - export WHITELIST=$${DEV_WHITELIST}
      - export KUBE_NAMESPACE=$${DEV_FORM_BUILDER_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export FORM_BUILDER_APP_CONFIG=$${DEV_FORM_BUILDER_APP_CONFIG}
      - export FORM_BUILDER_PORT=$${DEV_FORM_BUILDER_PORT}
      - export FORM_BUILDER_IMAGE_TAG=${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: dev
      event: deployment

  deploy_to_production:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PRODUCTION_FORM_BUILDER_NAME
      - PRODUCTION_WHITELIST
      - PRODUCTION_FORM_BUILDER_KUBE_NAMESPACE
      - PRODUCTION_KUBE_SERVER
      - PRODUCTION_KUBE_TOKEN
      - PRODUCTION_FORM_BUILDER_APP_CONFIG
      - PRODUCTION_FORM_BUILDER_PORT
    commands:
      - export FORM_BUILDER_NAME=$${PRODUCTION_FORM_BUILDER_NAME}
      - export WHITELIST=$${PRODUCTION_WHITELIST}
      - export KUBE_NAMESPACE=$${PRODUCTION_FORM_BUILDER_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${PRODUCTION_KUBE_SERVER}
      - export KUBE_TOKEN=$${PRODUCTION_KUBE_TOKEN}
      - export FORM_BUILDER_APP_CONFIG=$${PRODUCTION_FORM_BUILDER_APP_CONFIG}
      - export FORM_BUILDER_PORT=$${PRODUCTION_FORM_BUILDER_PORT}
      - export FORM_BUILDER_IMAGE_TAG=${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: production
      event: deployment
