kind: pipeline
name: default

## Build Public Image
steps:
- name: test
  image: digitalpatterns/node:4
  commands:
    - npm install
    - npm run test
  when:
    branch:
      - master
    event:
      - push

- name: cypress
  image: digitalpatterns/node:4
  commands:
    - npm run cypress:open
  when:
    branch:
      - master
    event:
      - push

- name: image_to_docker_hub
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: digitalpatterns/form-builder
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
  when:
    branch:
      - master
    event:
      - push
