kind: pipeline
name: default

## Build Public Image
steps:
- name: test
  image: plugins/docker
  environment:
    USERNAME:
      from_secret: docker_username
  commands:
  - echo $USERNAME

- name: image_to_docker_hub
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_password: docker_password
    repo: digitalpatterns/form-builder
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
  when:
    branch:
      - master
    event:
      - push
