pipeline:

## Build Public Image
  image_to_docker_hub:
    image: plugins/docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    settings:
      repo: digitalpatterns/form-builder
      username:
        from_secret: docker_username
      password:
        from_password: docker_password
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_SHA}
        - latest
    when:
      branch:
        - master
      event:
        - push
