---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.FORM_BUILDER_NAME}}
spec:
  selector:
    matchLabels:
      name: {{.FORM_BUILDER_NAME}}
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: {{.FORM_BUILDER_NAME}}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: proxy
        image: {{.NGINX_PROXY_IMAGE_REPO}}:{{.NGINX_PROXY_IMAGE_TAG}}
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: "{{.FORM_BUILDER_PORT}}"
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443
      - name: {{.FORM_BUILDER_NAME}}
        image: {{.FORM_BUILDER_IMAGE_REPO}}:{{.FORM_BUILDER_IMAGE_TAG}}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{.FORM_BUILDER_PORT}}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: {{.FORM_BUILDER_PORT}}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config
          name: config-volume
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: formbuilder

