---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.FORMBUILDER_NAME}}
spec:
  selector:
    matchLabels:
      name: {{.FORMBUILDER_NAME}}
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: {{.FORMBUILDER_NAME}}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      imagePullSecrets:
        - name: {{.DOCKER_CREDENTIALS}}
      containers:
      - name: proxy
        image: {{.NGINX_IMAGE}}:{{.NGINX_TAG}}
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: "{{.FORMBUILDER_PORT}}"
          - name: SERVER_CERT
            value: "/certs/tls.crt"
          - name: SERVER_KEY
            value: "/certs/tls.key"
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
      - name: {{.FORMBUILDER_NAME}}
        image: {{.FORMBUILDER_IMAGE}}:{{.FORMBUILDER_TAG}}
        imagePullPolicy: Always
        env:
          - name: FORMBUILDER_PORT
            value: "{{.FORMBUILDER_PORT}}"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{.FORMBUILDER_PORT}}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: {{.FORMBUILDER_PORT}}
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config
          name: config-volume
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: formbuilder
      - name: certs
        secret:
          secretName: "{{.FORMBUILDER_NAME}}-pod-tls"
