apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/backend-protocol: HTTPS
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-read-timeout: "3600"
    ingress.kubernetes.io/proxy-send-timeout: "3600"
#    ingress.kubernetes.io/whitelist-source-range: {{.WHITELIST}}
    kubernetes.io/ingress.class: nginx-external
    stable.k8s.psg.io/kcm.provider: http
  labels:
    app.kubernetes.io/name: {{.FORMBUILDER_NAME}}
    stable.k8s.psg.io/kcm.class: default
  name: {{.FORMBUILDER_NAME}}
spec:
  rules:
  - host: {{.FORMBUILDER_URL}}
    http:
      paths:
      - backend:
          serviceName: {{.FORMBUILDER_NAME}}
          servicePort: 443
  tls:
  - hosts:
    - {{.FORMBUILDER_URL}}
    secretName: {{.FORMBUILDER_URL}}-cmio
