apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: {{.FORMBUILDER_NAME}}
spec:
  podSelector:
    matchLabels:
      name: {{.FORMBUILDER_NAME}}
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-external
    ports:
    - port: 10443
      protocol: TCP
